resource_types:

  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: git-repo
    type: git
    webhook_token: token
    source:
      uri: ((postman-task-git-uri))
      branch: master
      username: ((git-username))
      password: ((git-password))

  - name: email
    type: email
    source:
      smtp:
        host: ((smtp-address))
        port: ((smtp-port))
        username: ((email-username))
        password: ((email-password))
      from: ((email-address))
      to: ((email-destination))

jobs:
  - name: test-postman
    plan:
      - get: git-repo
      
      - task: run-postman
        file: git-repo/postman-task.yml
        params:
          script: git-repo/test/postman_collection_fails.json
          html_report_template: git-repo/test/template/awesome-template.hbs
  
      - put: email
        params:
          subject_text: "Testing finished"
          body_text: "Testing is finished"
          attachment_globs: [ "results/*.html" ]
